#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$PATH:~/bin
eval "$(fasd --init auto)"
autoload -U compinit && compinit

export GITHUB_HOST=github.ewr01.tumblr.net
export GITHUB_URL=https://github.ewr01.tumblr.net/

[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
