#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

for config_file ($HOME/.yadr/zsh/*.zsh); do
  source $config_file;
done

export PATH=$PATH:~/bin
eval "$(fasd --init auto)"
autoload -U compinit && compinit

export GITHUB_HOST=github.tumblr.net
export GITHUB_URL=https://github.tumblr.net/

for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file
